// ============================================================
// Adv Class C — Module 1: Advanced Tense Dynamics & Aspectual Choice
// Activities 1–10: Performatives, State/Action Shifts & Narrative Layering
// ============================================================

import { AdvancedClass } from './types';

export const advClassC: AdvancedClass = {
  id: 'adv-class-c',
  letter: 'C',
  moduleNumber: 3,
  name: 'Adv Class C',
  title: 'Advanced Tense Dynamics & Aspectual Choice',
  theme: 'Grammar Dynamics & Aspectual Precision',
  overview:
    'Grounded in Martin Hewings’ Advanced Grammar in Use framework, this module masters high-level tense dynamics: speech-act performatives in formal business correspondence, subtle state-versus-continuous mental shifts ("regret" vs. "am regretting"), sports commentary temporal layering, and narrative immediacy via the historic present.',
  linguistNote:
    'At the C1-C2 boundary, grammatical proficiency moves beyond rule compliance into deliberate pragmatic choice. Choosing continuous aspect for typically stative verbs ("loving having him", "considering") signals temporary duration or psychological tentativeness, while performative verbs ("I request", "we guarantee") establish authoritative legal and institutional standing.',
  activitiesCount: 10,
  cefrRange: 'C1–C2',
  isReady: true,
  activities: [
    {
      id: 'adv-c-1',
      activityNumber: 1,
      globalNumber: 21,
      title: 'The Corporate Performative',
      skill: 'Writing',
      subskill: 'Present Simple Performative Verbs',
      cefrLevel: 'C1',
      objective: 'Use performatives to establish a formal tone in professional correspondence.',
      instructions: 'Rewrite the informal directive using the performative verb suggest, request, or guarantee.',
      taskPrompt: 'Rewrite: "I’m telling you to read the contract first."',
      expectedAnswer: 'I suggest that you read the contract first.',
      targetCollocation: 'suggest / request / performative verb',
      difficulty: 'Advanced',
      activityType: 'Register Shift',
      justification:
        'Performative verbs in the present simple (suggest, request, advise) perform the action as they are uttered, establishing diplomatic institutional authority without conversational bluntness.',
      hint: 'Use the performative verb "suggest" or "request" in the first person: "I suggest that you..."',
      xpReward: 20,
    },
    {
      id: 'adv-c-2',
      activityNumber: 2,
      globalNumber: 22,
      title: 'The Evolution of Regret',
      skill: 'Writing',
      subskill: 'Mental State Verbs (State vs. Continuous)',
      cefrLevel: 'C2',
      objective: 'Distinguish between a settled decision and a developing realization.',
      instructions: 'Create two sentences for the verb regret, one using simple and one continuous, to show different mental states.',
      taskPrompt: 'Context: A CEO discussing a past merger versus a current, ongoing mistake.',
      expectedAnswer: 'I regret that the merger occurred. / I’m regretting the decision as the losses mount.',
      targetCollocation: 'regret (settled) vs. am regretting (developing)',
      difficulty: 'Mastery',
      activityType: 'Nuanced Expression',
      justification:
        'Present simple "I regret" frames the feeling as an established, permanent stance, whereas continuous "I am regretting" highlights an unfolding, intensifying psychological process.',
      hint: 'Contrast a permanent past admission ("I regret that...") with an ongoing progressive reaction ("I am regretting... as...").',
      xpReward: 25,
    },
    {
      id: 'adv-c-3',
      activityNumber: 3,
      globalNumber: 23,
      title: 'Thinking Process vs. Opinion',
      skill: 'Speaking',
      subskill: 'Consider as an Action Verb',
      cefrLevel: 'C1',
      objective: 'Apply the present continuous to describe active deliberation.',
      instructions: 'Answer a career question using considering to show you haven\'t decided yet.',
      taskPrompt: 'Are you going to accept the promotion?',
      expectedAnswer: 'I’m considering taking it, but I need more time.',
      targetCollocation: 'am considering (active deliberation)',
      difficulty: 'Advanced',
      activityType: 'Real-world Application',
      justification:
        'While "consider" meaning "hold an opinion" is stative ("I consider it wise"), using the continuous "am considering" converts the verb into an active mental deliberation.',
      hint: 'Speak your response using "I am considering..." followed by a condition or pause.',
      xpReward: 20,
    },
    {
      id: 'adv-c-4',
      activityNumber: 4,
      globalNumber: 24,
      title: 'Temporary Affection',
      skill: 'Writing',
      subskill: 'State Verbs in Continuous for Temporariness',
      cefrLevel: 'C2',
      objective: 'Use the present continuous with love or like to emphasize a short-term situation.',
      instructions: 'Describe a guest\'s visit using a continuous state verb.',
      taskPrompt: 'Context: A friend staying for just one weekend.',
      expectedAnswer: 'He’s staying for two days and the kids are loving having him here.',
      targetCollocation: 'are loving (temporary enjoyment)',
      difficulty: 'Mastery',
      activityType: 'Aspectual Choice',
      justification:
        'Employing the continuous aspect with emotion verbs like "love" or "like" signals that the enjoyment is tied specifically to a temporary, transient window rather than an enduring trait.',
      hint: 'Combine the short-term stay with "the kids are loving having him here".',
      xpReward: 25,
    },
    {
      id: 'adv-c-5',
      activityNumber: 5,
      globalNumber: 25,
      title: 'Live Commentary Precision',
      skill: 'Speaking',
      subskill: 'Present Simple/Continuous for Sports',
      cefrLevel: 'C1',
      objective: 'Narrate rapid actions vs. developing play.',
      instructions: 'Describe a tennis match scene using two different tenses.',
      taskPrompt: 'Prompt: The serve and the subsequent rally.',
      expectedAnswer: 'Federer serves to the left; he\'s playing magnificent tennis today.',
      targetCollocation: 'serves (simple: rapid) / is playing (continuous: background)',
      difficulty: 'Advanced',
      activityType: 'Production',
      justification:
        'Live sports broadcasting uses present simple for instantaneous discrete actions ("serves", "shoots") and present continuous for background unfolding form ("he is playing").',
      hint: 'Deliver a quick broadcast sentence: use present simple for the stroke, then continuous for the overall form.',
      xpReward: 20,
    },
    {
      id: 'adv-c-6',
      activityNumber: 6,
      globalNumber: 26,
      title: 'The News Informant',
      skill: 'Speaking',
      subskill: 'Reporting News (I gather/I see)',
      cefrLevel: 'C1',
      objective: 'Introduce news using present tense reporting phrases.',
      instructions: 'Use "I see" or "I hear" to comment on a recent headline.',
      taskPrompt: 'Context: A government funding increase.',
      expectedAnswer: 'I see the government is giving the health service more money.',
      targetCollocation: 'I see / I hear (conversational reporting)',
      difficulty: 'Advanced',
      activityType: 'Functional Language',
      justification:
        'Present simple sensory verbs ("I see", "I hear", "I gather") function idiomatically to introduce second-hand information or newly digested media reports.',
      hint: 'Open your spoken sentence with "I see..." or "I hear..." followed by the news update.',
      xpReward: 20,
    },
    {
      id: 'adv-c-7',
      activityNumber: 7,
      globalNumber: 27,
      title: 'The Anecdotal "Jump"',
      skill: 'Speaking',
      subskill: 'Present Simple in Informal Narratives',
      cefrLevel: 'C2',
      objective: 'Create immediacy in storytelling.',
      instructions: 'Narrate a sudden event in a story using the present simple.',
      taskPrompt: 'Context: Sitting in a park when a dog approaches.',
      expectedAnswer: 'I’m sitting there, minding my own business, when all of a sudden this dog jumps at me.',
      targetCollocation: 'historic present / jumps at me',
      difficulty: 'Mastery',
      activityType: 'Narrative Style',
      justification:
        'The historic present abruptly shifts from continuous past backgrounding to dramatic simple present, injecting visceral tension and listener immersion.',
      hint: 'Set the scene with continuous past/present, then deliver the sudden action in present simple: "this dog jumps at me".',
      xpReward: 25,
    },
    {
      id: 'adv-c-8',
      activityNumber: 8,
      globalNumber: 28,
      title: 'Chronological Correction',
      skill: 'Writing',
      subskill: 'Present Perfect vs. Past Simple (Since-clauses)',
      cefrLevel: 'C1',
      objective: 'Correct tense usage in complex time clauses.',
      instructions: 'Identify and rectify the aspectual error in the time clause.',
      taskPrompt: 'Fix the sentence: "Since I have moved here, I met many people."',
      expectedAnswer: 'Since I moved here, I have met many people.',
      targetCollocation: 'Since + past simple, present perfect',
      difficulty: 'Advanced',
      activityType: 'Error Correction',
      justification:
        'In "since"-clauses marking a specific starting point in time, the dependent clause requires past simple ("since I moved"), while the main clause requires present perfect ("I have met").',
      hint: 'The action in the since-clause is a finished starting point (past simple), and the cumulative result uses present perfect.',
      xpReward: 20,
    },
    {
      id: 'adv-c-9',
      activityNumber: 9,
      globalNumber: 29,
      title: 'The Unfinished Morning',
      skill: 'Writing',
      subskill: 'Present Perfect for Unfinished Time Periods',
      cefrLevel: 'C1',
      objective: 'Distinguish between a completed past and a period including the present.',
      instructions: 'Contrast shaved and haven\'t shaved based on whether the morning is still ongoing.',
      taskPrompt: 'It is 11:00 AM. Write a sentence about your grooming.',
      expectedAnswer: 'I haven’t shaved this morning.',
      targetCollocation: 'haven’t shaved (unfinished time period)',
      difficulty: 'Advanced',
      activityType: 'Contextual Choice',
      justification:
        'At 11:00 AM, "this morning" is still in progress; therefore, the present perfect ("haven’t shaved") is grammatically compulsory, unlike afternoon retrospective past simple ("didn\'t shave").',
      hint: 'Because it is still morning (11:00 AM), use present perfect: "I haven\'t shaved this morning."',
      xpReward: 20,
    },
    {
      id: 'adv-c-10',
      activityNumber: 10,
      globalNumber: 30,
      title: 'The "First Time" Rule',
      skill: 'Writing',
      subskill: 'Present Perfect after It is the first time',
      cefrLevel: 'C1',
      objective: 'Apply the correct perfect aspect after specific introductory phrases.',
      instructions: 'Complete the sentence about a novel encounter using the required aspect.',
      taskPrompt: 'Complete: "This is the first time..." (see Jan look embarrassed).',
      expectedAnswer: 'This is the first time I’ve seen Jan look embarrassed.',
      targetCollocation: 'This is the first time + I have seen',
      difficulty: 'Advanced',
      activityType: 'Task Prompt',
      justification:
        'Formulaic evaluations of experiential frequency ("This is the first/second time...") strictly require present perfect in contemporary standard English.',
      hint: 'Follow "This is the first time" with the present perfect form: "I\'ve seen Jan look embarrassed."',
      xpReward: 20,
    },
  ],
};
