// ============================================================
// Adv Class B — Module 1: Research Architecture & Title Planning
// Activities 1–10: Instructional Analysis & Strategic Proportions
// ============================================================

import { AdvancedClass } from './types';

export const advClassB: AdvancedClass = {
  id: 'adv-class-b',
  letter: 'B',
  moduleNumber: 2,
  name: 'Adv Class B',
  title: 'Research Architecture & Title Planning',
  theme: 'Academic Writing & Prompt Deconstruction',
  overview:
    'Master the foundational mechanics of C1-C2 academic research and essay architecture. Learn to dissect complex prompts into Instruction, Subject, and Context components using the Bailey framework. Master strategic brainstorming, point-impact matrices, and proportional word-count weighting (the 20% rule) for balanced, high-scoring academic and professional papers.',
  linguistNote:
    'Academic prompts at the C1-C2 level demand immediate identification of instructional verbs ("evaluate", "summarise", "illustrate") and contextual boundaries (chronological, geographical, or developmental). Disproportionate word allocation or failure to isolate implicit context undermines research validity before writing even begins.',
  activitiesCount: 10,
  cefrRange: 'C1–C2',
  isReady: true,
  activities: [
    {
      id: 'adv-b-1',
      activityNumber: 1,
      globalNumber: 1,
      title: 'Structural Deconstruction of E-Commerce Growth',
      skill: 'Research Architecture',
      subskill: 'Instructional Analysis',
      cefrLevel: 'C1',
      objective: 'To identify the core components of a research prompt using the Bailey framework.',
      instructions: 'Analyze the prompt and categorize its components into the Instruction/Subject/Context table.',
      taskPrompt: 'Summarise the main reasons for the growth of e-commerce since 2010 and discuss the likely results of this.',
      expectedAnswer:
        'Instruction: Summarise (Description) / Discuss (Evaluation)\nSubject: Growth of e-commerce / Likely results\nContext: Chronological (since 2010)',
      targetCollocation: 'Instruction / Subject / Context',
      difficulty: 'Advanced',
      activityType: 'Analysis',
      justification:
        'The Bailey framework isolates the directive operations (Summarise & Discuss), the thematic phenomena under review (e-commerce growth & future consequences), and the empirical boundary parameter (since 2010).',
      hint: 'Categorize into Instruction (directive verbs), Subject (core phenomena), and Context (temporal/spatial boundaries).',
      xpReward: 20,
    },
    {
      id: 'adv-b-2',
      activityNumber: 2,
      globalNumber: 2,
      title: 'Medical Adherence: Diagnostic Title Breakdown',
      skill: 'Research Architecture',
      subskill: 'Instructional Analysis',
      cefrLevel: 'C1',
      objective: 'Distinguish between descriptive instructions and specific research subjects.',
      instructions: 'Map the following prompt into the required structural framework.',
      taskPrompt: 'Describe some of the reasons why patients do not always take their medication as directed.',
      expectedAnswer:
        'Instruction: Describe (Give a detailed account)\nSubject: Reasons for non-adherence to medication\nContext: Not specified (General medical context)',
      targetCollocation: 'Describe / non-adherence',
      difficulty: 'Advanced',
      activityType: 'Analysis',
      justification:
        'Recognizing an unspecified context prevents arbitrary narrowing; the researcher must treat the inquiry across general clinical outpatient settings.',
      hint: 'Notice the single instruction verb "Describe" and the subject of clinical non-adherence.',
      xpReward: 20,
    },
    {
      id: 'adv-b-3',
      activityNumber: 3,
      globalNumber: 3,
      title: 'Identifying Implicit Contexts in L2 Acquisition',
      skill: 'Research Architecture',
      subskill: 'Instructional Analysis',
      cefrLevel: 'C2',
      objective: 'Identify both explicit and implicit contexts within a multi-part prompt.',
      instructions: 'Analyze the title for instructions and subjects, noting the developmental context.',
      taskPrompt:
        'What are the benefits of learning a second language at primary school (age 6–10)? Are there any drawbacks to early language learning?',
      expectedAnswer:
        'Instruction: What (Identify/List) / Are there (Evaluate/Discuss)\nSubject: Benefits and drawbacks of L2 acquisition\nContext: Explicit: Primary school (Age 6-10). Implicit: Cognitive/educational development.',
      targetCollocation: 'Explicit / Implicit Context',
      difficulty: 'Mastery',
      activityType: 'Analysis',
      justification:
        'Advanced scholarship demands parsing unstated assumptions; "primary school (6-10)" inherently introduces developmental psychology and neural plasticity constraints.',
      hint: 'Specify both the explicit chronological age and the implicit cognitive development context.',
      xpReward: 25,
    },
    {
      id: 'adv-b-4',
      activityNumber: 4,
      globalNumber: 4,
      title: 'Evaluating Renewables: Quantitative Context Mapping',
      skill: 'Research Architecture',
      subskill: 'Instructional Analysis',
      cefrLevel: 'C2',
      objective: 'Break down a prompt that requires both empirical identification and critical evaluation.',
      instructions: 'Use the Bailey framework to define the scope of the essay.',
      taskPrompt:
        'What are the most significant sources of renewable energy? Evaluate their contribution to the reduction of carbon emissions in the last 15 years.',
      expectedAnswer:
        'Instruction: What (Identify) / Evaluate (Decide worth/value)\nSubject: Sources of renewable energy / CO2 reduction\nContext: Chronological (Last 15 years)',
      targetCollocation: 'Identify / Evaluate / CO2 reduction',
      difficulty: 'Mastery',
      activityType: 'Analysis',
      justification:
        '"Evaluate" signals high-stakes academic critique (appraising efficacy against quantitative emission benchmarks within a strict 15-year longitudinal window).',
      hint: 'Two-part instruction: identifying energy sources and critically evaluating 15-year CO2 reduction.',
      xpReward: 25,
    },
    {
      id: 'adv-b-5',
      activityNumber: 5,
      globalNumber: 5,
      title: 'Strategic Brainstorming: The L2 Advantage',
      skill: 'Research Architecture',
      subskill: 'Strategic Brainstorming',
      cefrLevel: 'C1',
      objective: 'Generate a balanced list of points for a dual-focus prompt.',
      instructions: 'Based on Title 3c, generate four benefits and three drawbacks of early language learning.',
      taskPrompt: 'Brainstorm points for the "Primary School L2" essay.',
      expectedAnswer:
        'Benefits: 1. Lowered inhibitions; 2. Superior memory capacity; 3. Enhanced understanding of L1; 4. Cultural open-mindedness.\nDrawbacks: 1. Grammatical confusion; 2. Lack of cultural context; 3. Curriculum time conflicts.',
      targetCollocation: 'Inhibitions / Memory capacity / Cultural open-mindedness',
      difficulty: 'Advanced',
      activityType: 'Production',
      justification:
        'A dual-focus essay requires balanced preliminary mapping across affective, cognitive, and institutional domains before drafting.',
      hint: 'Structure exactly 4 concise benefits and 3 logistical/pedagogical drawbacks.',
      xpReward: 20,
    },
    {
      id: 'adv-b-6',
      activityNumber: 6,
      globalNumber: 6,
      title: 'Energy Matrix: Source vs. Impact',
      skill: 'Research Architecture',
      subskill: 'Strategic Brainstorming',
      cefrLevel: 'C1',
      objective: 'Link specific sources of energy to their environmental viability.',
      instructions: 'List renewable sources and their carbon impact based on the "Renewable Energy" theme.',
      taskPrompt: 'Create a point-impact list for renewable sources.',
      expectedAnswer:
        'Wind: High availability day/night but remote sites.\nSolar: Significant in sunny areas; zero night production.\nTidal: Massive potential but remains in development.\nBiomass: Established but competes for scarce agricultural land.',
      targetCollocation: 'Wind / Solar / Tidal / Biomass impact matrix',
      difficulty: 'Advanced',
      activityType: 'Production',
      justification:
        'Scholarly brainstorming links each technological solution directly to its engineering trade-off and land-use externalities.',
      hint: 'Map Wind, Solar, Tidal, and Biomass with their operational limitations.',
      xpReward: 20,
    },
    {
      id: 'adv-b-7',
      activityNumber: 7,
      globalNumber: 7,
      title: 'E-commerce Drivers Mind-Mapping',
      skill: 'Research Architecture',
      subskill: 'Strategic Brainstorming',
      cefrLevel: 'C1',
      objective: 'Categorize geographic and technological drivers for industry growth.',
      instructions: 'Use the "British Shoppers Go Online" text to find three growth factors.',
      taskPrompt: 'Brainstorm growth drivers for UK e-commerce.',
      expectedAnswer:
        'Geography: Small, densely populated (optimized for delivery).\nTechnology: Ubiquity and convenience of smartphones.\nLogistics: Expansion of massive fulfillment centers and efficient parcel management.',
      targetCollocation: 'Geography / Technology / Logistics',
      difficulty: 'Advanced',
      activityType: 'Production',
      justification:
        'Categorizing drivers into macro-factors (Geography, Technology, Logistics) creates ready-made topic sentences for body paragraphs.',
      hint: 'Group drivers into Geography (density), Technology (smartphones), and Logistics (fulfillment).',
      xpReward: 20,
    },
    {
      id: 'adv-b-8',
      activityNumber: 8,
      globalNumber: 8,
      title: 'Proportional Planning: The 20% Rule',
      skill: 'Research Architecture',
      subskill: 'Proportional Planning',
      cefrLevel: 'C1',
      objective: 'Calculate logical word-count allocations using the framing rule.',
      instructions: 'For a 2,000-word essay, allocate word counts and explain the rationale based on Unit 1.5.5.',
      taskPrompt: 'Create a plan for a 2,000-word essay on L2 benefits.',
      expectedAnswer:
        'Intro/Conclusion (400 words): Follows the 20% rule to provide the frame.\nMain Body (1,600 words): Must address "Benefits" and "Drawbacks" proportionally.\nBenefits Section (approx. 900 words): Covers the three detailed points.\nDrawbacks Section (approx. 700 words): Addresses the counter-points.',
      targetCollocation: '20% Rule / Main Body Proportions',
      difficulty: 'Advanced',
      activityType: 'Transformation',
      justification:
        'The 20% framing rule reserves 10% for Introduction and 10% for Conclusion, preventing over-extended preambles and preserving wordcount for evidence.',
      hint: 'Allocate 20% (400 words) for Intro/Conclusion and split 1,600 words between Benefits and Drawbacks.',
      xpReward: 20,
    },
    {
      id: 'adv-b-9',
      activityNumber: 9,
      globalNumber: 9,
      title: 'Evaluative Balance: Tourism Impacts',
      skill: 'Research Architecture',
      subskill: 'Proportional Planning',
      cefrLevel: 'C2',
      objective: 'Balance descriptive and prescriptive sections in a professional essay.',
      instructions: 'Allocate percentages for the main body for the tourism prompt.',
      taskPrompt: 'Describe the typical social... impacts. How can harmful impacts be reduced?',
      expectedAnswer:
        'Part 1 (Impact Description): 50% (Requires synthesis of three distinct areas).\nPart 2 (Reduction Strategies): 50% (Requires original evaluation of solutions).',
      targetCollocation: '50% Descriptive / 50% Evaluative',
      difficulty: 'Mastery',
      activityType: 'Transformation',
      justification:
        'Equal weighting ensures equitable attention to diagnosis (social impacts) and remedy (mitigation policies), preventing lopsided essays.',
      hint: 'Allocate an exact 50/50 balance between descriptive diagnostic impacts and reduction strategies.',
      xpReward: 25,
    },
    {
      id: 'adv-b-10',
      activityNumber: 10,
      globalNumber: 10,
      title: 'Justifying Proportions: IT in Schools',
      skill: 'Research Architecture',
      subskill: 'Proportional Planning',
      cefrLevel: 'C2',
      objective: 'Defend the structural weighting of an essay based on instruction words.',
      instructions: 'Allocate percentages for the following title and justify the weighting.',
      taskPrompt: 'How can schools make better use of IT? Illustrate with examples from one country.',
      expectedAnswer:
        'Section 1 (General Methods): 40%.\nSection 2 (Country Illustration): 60%.\nRationale: The instruction "Illustrate" requires the bulk of the content to be situated within the specific context of the chosen country to prove the general methods\' viability.',
      targetCollocation: '40% General / 60% Case Illustration',
      difficulty: 'Mastery',
      activityType: 'Transformation',
      justification:
        'The directive "Illustrate" places the primary burden of proof on the empirical national case study, mandating a 60% substantive weighting.',
      hint: 'The instruction "Illustrate" demands a 40/60 distribution favoring the empirical country example.',
      xpReward: 25,
    },
  ],
};
