// ============================================================
// Adv Class A — Module 1: Advanced Register & Formality Upgrades
// Activities 1–10: Register Refinement
// ============================================================

import { AdvancedClass } from './types';

export const advClassA: AdvancedClass = {
  id: 'adv-class-a',
  letter: 'A',
  moduleNumber: 1,
  name: 'Adv Class A',
  title: 'Advanced Register & Formality Upgrades',
  theme: 'Register Refinement',
  overview:
    'In the sphere of professional English, register flexibility is not merely a linguistic asset; it is a strategic tool for establishing authority and institutional belonging. The ability to navigate between informal spoken discourse and the precise, often legalistic, terminology of official notices signals a high level of communicative competence. Shifting from common phrasal verbs like "get off" to "alight from" or "throw away" to "dispose of" demonstrates a mastery of context that is essential for leadership and administrative roles. This module focuses on refining this sensitivity to register, ensuring that the learner can calibrate their language to meet the rigorous demands of professional environments.',
  linguistNote:
    'Newspaper English collocations such as "axe jobs" or "slashes prices" are designed for maximum dramatic impact within restrictive character counts. While highly effective for capturing attention, they differ significantly from standard business prose, which favors more measured collocations like "make redundant" or "reduce costs." Mastering these distinctions allows a professional to choose between the urgency of a headline and the institutional stability of a formal report. Mastering register is the foundational step toward achieving the precision and nuance required for executive-level communication.',
  activitiesCount: 10,
  cefrRange: 'C1–C2',
  isReady: true,
  activities: [
    {
      id: 'adv-a-1',
      activityNumber: 1,
      globalNumber: 1,
      title: 'Transit Protocol',
      skill: 'Writing',
      subskill: 'Formal Notices',
      cefrLevel: 'C1',
      objective: 'Use formal transit collocations.',
      instructions: 'Rewrite a municipal bus directive for an official city ordinance.',
      taskPrompt: "Don't get off while the bus is moving.",
      expectedAnswer: 'Passengers must not alight from the bus while it is in motion.',
      targetCollocation: 'alight from / in motion',
      difficulty: 'Advanced',
      activityType: 'Register Shift',
      justification:
        "'Alight from' replaces colloquial 'get off', and 'in motion' elevates 'moving' into standard formal transit ordinances.",
      hint: "Replace 'get off' with the formal verb beginning with 'alight...' and 'moving' with 'in motion'.",
      xpReward: 20,
    },
    {
      id: 'adv-a-2',
      activityNumber: 2,
      globalNumber: 2,
      title: 'Waste Management',
      skill: 'Writing',
      subskill: 'Regulatory Policy',
      cefrLevel: 'C2',
      objective: 'Apply legalistic disposal terms.',
      instructions: 'Draft a corporate policy for industrial battery disposal.',
      taskPrompt: 'Put unwanted batteries in the bin we gave you.',
      expectedAnswer: 'Please dispose of unwanted items in the receptacle provided.',
      targetCollocation: 'dispose of / receptacle provided',
      difficulty: 'Mastery',
      activityType: 'Policy Drafting',
      justification:
        "'Dispose of' is the statutory regulatory term for discarding waste, and 'receptacle provided' replaces casual 'bin we gave you'.",
      hint: "Use 'dispose of' instead of 'put' and 'receptacle provided' instead of 'bin'.",
      xpReward: 25,
    },
    {
      id: 'adv-a-3',
      activityNumber: 3,
      globalNumber: 3,
      title: 'Press Release: Jobs',
      skill: 'Writing',
      subskill: 'Journalism',
      cefrLevel: 'C1',
      objective: 'Use dramatic media collocations.',
      instructions: 'Transform a standard corporate announcement into a punchy news headline.',
      taskPrompt: 'The company is going to make 200 people redundant.',
      expectedAnswer: 'COMPUTER FACTORY TO AXE JOBS',
      targetCollocation: 'axe jobs',
      difficulty: 'Advanced',
      activityType: 'Headline Transformation',
      justification:
        "'Axe jobs' is the canonical high-impact journalistic collocation used in headlines for rapid comprehension and dramatic weight.",
      hint: "Use an all-caps punchy headline format with 'AXE JOBS'.",
      xpReward: 20,
    },
    {
      id: 'adv-a-4',
      activityNumber: 4,
      globalNumber: 4,
      title: 'Pricing Strategy',
      skill: 'Writing',
      subskill: 'Business Comms',
      cefrLevel: 'C1',
      objective: 'Apply impact-oriented verbs.',
      instructions: 'Rewrite a discount announcement for an industry journal.',
      taskPrompt: 'The airline has decided to cut prices drastically.',
      expectedAnswer: 'AIRLINE SLASHES PRICES',
      targetCollocation: 'slashes prices',
      difficulty: 'Advanced',
      activityType: 'Register Shift',
      justification:
        "'Slash prices' provides dynamic commercial impact and brevity compared to verbose phrases like 'cut prices drastically'.",
      hint: "Formulate a concise headline with the active verb 'SLASHES'.",
      xpReward: 20,
    },
    {
      id: 'adv-a-5',
      activityNumber: 5,
      globalNumber: 5,
      title: 'Market Forecasts',
      skill: 'Speaking',
      subskill: 'Executive Briefing',
      cefrLevel: 'C2',
      objective: 'Use high-level movement terms.',
      instructions: 'Brief the board on rapid budget increases using financial metaphors.',
      taskPrompt: 'Government spending will increase very fast this year.',
      expectedAnswer: 'Government spending will rocket this year.',
      targetCollocation: 'rocket',
      difficulty: 'Mastery',
      activityType: 'Scenario Simulation',
      justification:
        "'Rocket' functions as an evocative, high-velocity movement verb signaling steep, exponential growth in economic contexts.",
      hint: "Use the metaphorical verb 'rocket' to convey rapid, steep increase.",
      xpReward: 25,
    },
    {
      id: 'adv-a-6',
      activityNumber: 6,
      globalNumber: 6,
      title: 'Legal Warnings',
      skill: 'Writing',
      subskill: 'Law Enforcement',
      cefrLevel: 'C1',
      objective: 'Use performative legal phrases.',
      instructions: 'Draft a warning sign for a private secure facility.',
      taskPrompt: 'People who walk here without asking will be taken to court.',
      expectedAnswer: 'Trespassers will be prosecuted.',
      targetCollocation: 'trespassers will be prosecuted',
      difficulty: 'Advanced',
      activityType: 'Legal Framing',
      justification:
        "'Trespassers will be prosecuted' is a standard performative legal utterance carrying statutory enforceability.",
      hint: "Think of the standard 4-word legal notice starting with 'Trespassers...'.",
      xpReward: 20,
    },
    {
      id: 'adv-a-7',
      activityNumber: 7,
      globalNumber: 7,
      title: 'Procurement Basics',
      skill: 'Writing',
      subskill: 'Contractual English',
      cefrLevel: 'C2',
      objective: 'Use procurement terminology.',
      instructions: 'Synthesize a sentence regarding the formal bidding process for a state project.',
      taskPrompt: 'We need to send in a document stating our price for the job.',
      expectedAnswer: 'We must submit a tender for the new stadium.',
      targetCollocation: 'submit a tender',
      difficulty: 'Mastery',
      activityType: 'Register Shift',
      justification:
        "'Submit a tender' is the official commercial and contractual collocation for formal competitive bids.",
      hint: "Use the procurement phrase 'submit a tender'.",
      xpReward: 25,
    },
    {
      id: 'adv-a-8',
      activityNumber: 8,
      globalNumber: 8,
      title: 'Capital Acquisition',
      skill: 'Speaking',
      subskill: 'Finance',
      cefrLevel: 'C2',
      objective: 'Use funding collocations.',
      instructions: 'Describe the strategic necessity of securing expansion funds.',
      taskPrompt: 'We need to get money to expand our business.',
      expectedAnswer: 'We need to raise capital to expand.',
      targetCollocation: 'raise capital',
      difficulty: 'Mastery',
      activityType: 'Business Simulation',
      justification:
        "'Raise capital' replaces conversational 'get money' with formal institutional corporate finance terminology.",
      hint: "Replace 'get money' with the corporate finance collocation 'raise capital'.",
      xpReward: 25,
    },
    {
      id: 'adv-a-9',
      activityNumber: 9,
      globalNumber: 9,
      title: 'Institutional Entry',
      skill: 'Writing',
      subskill: 'Formal Signage',
      cefrLevel: 'C1',
      objective: 'Use formal physical instructions.',
      instructions: 'Create a formal instruction for a pedestrian bridge in a university setting.',
      taskPrompt: 'Bikers must get off their bikes here.',
      expectedAnswer: 'Cyclists must dismount here.',
      targetCollocation: 'cyclists must dismount',
      difficulty: 'Advanced',
      activityType: 'Register Shift',
      justification:
        "'Cyclists must dismount' is standard institutional English for pedestrian priority zones, replacing casual 'bikers'.",
      hint: "Use 'cyclists' and the formal action verb 'dismount'.",
      xpReward: 20,
    },
    {
      id: 'adv-a-10',
      activityNumber: 10,
      globalNumber: 10,
      title: 'Professional Inquiries',
      skill: 'Speaking',
      subskill: 'Media Interviews',
      cefrLevel: 'C2',
      objective: 'Use journalistic interview terms.',
      instructions: 'Question a person of interest for a formal investigative report.',
      taskPrompt: 'The police asked the man questions for hours.',
      expectedAnswer: 'Police quiz suspect in murder enquiry.',
      targetCollocation: 'quiz suspect / enquiry',
      difficulty: 'Mastery',
      activityType: 'Error Correction',
      justification:
        "'Quiz suspect' and 'enquiry' provide concise journalistic precision over generic 'asked questions for hours'.",
      hint: "Use the journalistic verb 'quiz' with 'suspect' and 'enquiry'.",
      xpReward: 25,
    },
  ],
};
